# Generated by Django 4.2.6 on 2023-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Evento')),
                ('data', models.CharField(max_length=200, verbose_name='Data')),
                ('luogo', models.CharField(max_length=200, verbose_name='Luogo')),
                ('img', models.ImageField(default='static/slide/no_img.jpeg', upload_to='slide/%Y/%m/%d', verbose_name='Immagine Slide')),
            ],
        ),
    ]
