# Generated by Django 4.2.6 on 2023-12-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('ora', models.TimeField()),
                ('luogo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('img', models.ImageField(default='static/slide/no_img.jpeg', upload_to='img_evento/%Y/%m/%d', verbose_name='Immagine Evento')),
            ],
        ),
    ]
