# Generated by Django 4.2.6 on 2023-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0002_eventi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventi',
            name='ora',
        ),
        migrations.AlterField(
            model_name='eventi',
            name='img',
            field=models.ImageField(default='static/logo.png', upload_to='img_evento/%Y/%m/%d', verbose_name='Immagine Evento'),
        ),
    ]
