# Generated by Django 4.2.6 on 2023-12-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0006_artisti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisti',
            old_name='foto',
            new_name='img',
        ),
    ]
