# Generated by Django 4.2.6 on 2023-12-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0008_candidati'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidati',
            old_name='eperienza',
            new_name='esperienza',
        ),
    ]
