# Generated by Django 4.2.6 on 2023-12-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0009_rename_eperienza_candidati_esperienza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisti',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_artisti', verbose_name='Foto Profilo'),
        ),
    ]
