# Generated by Django 4.2.6 on 2023-12-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0011_commenti_alter_candidati_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisti',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
