# Generated by Django 4.2.6 on 2023-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0012_alter_artisti_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(default='logo.png', upload_to='img_fotopage/%Y/%m/%d')),
            ],
        ),
    ]
