# Generated by Django 4.2.6 on 2023-12-20 15:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0015_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('cognome_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('citta', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci la sigla di una provincia (2 lettere)', regex='^[A-Za-z]{2}$')], verbose_name='Sigla provincia di residenza')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci un numero di cellulare (solo cifre, senza spazi)', regex='^\\d{,15}$')], verbose_name='Cellulare contatto')),
                ('tipo_evento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo di evento (matrimonio, compleanno...)')),
                ('luogo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Luogo/nome della sala')),
                ('citta_evento', models.CharField(max_length=200, verbose_name="Città dell'evento")),
                ('prov_evento', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci la sigla di una provincia (2 lettere)', regex='^[A-Za-z]{2}$')], verbose_name="Sigla provincia dell'evento")),
                ('indirizzo_evento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Via/Piazza e numero civico')),
                ('seleziona_artisti', models.CharField(choices=[('cantante', 'Cantante'), ('deejay', 'Deejay'), ('animatrica', 'Animatrice'), ('presentatore', 'Presentatore'), ('sax', 'Sax'), ('violino', 'Violino'), ('tastiera', 'Tastiera'), ('bassisat', 'Bassista'), ('percussioni', 'Percussioni'), ('batteria', 'Batteria')], default=' ', max_length=50, verbose_name='Seleziona artisti')),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
