# Generated by Django 4.2.6 on 2023-12-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0016_prenotaevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotaevento',
            name='data_evento',
            field=models.DateTimeField(),
        ),
    ]
