# Generated by Django 4.2.6 on 2023-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0017_alter_prenotaevento_data_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenti',
            name='commento',
            field=models.CharField(max_length=500),
        ),
    ]
