# Generated by Django 4.2.6 on 2023-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0018_alter_commenti_commento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenti',
            name='commento',
            field=models.TextField(max_length=500),
        ),
    ]
