# Generated by Django 4.2.6 on 2023-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0019_alter_commenti_commento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ruoli',
            },
        ),
    ]
