# Generated by Django 4.2.6 on 2023-12-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0020_ruolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisti',
            name='ruolo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='artista', to='gruppo.ruolo', unique=True),
        ),
    ]
