# Generated by Django 4.2.6 on 2023-12-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0022_remove_artisti_ruolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisti',
            name='ruolo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='componente', to='gruppo.ruolo'),
        ),
    ]
