# Generated by Django 4.2.6 on 2023-12-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0025_remove_artisti_ruolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisti',
            name='ruolo',
            field=models.ManyToManyField(to='gruppo.ruolo'),
        ),
    ]
