# Generated by Django 4.2.6 on 2023-12-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0027_alter_ruolo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisti',
            name='ruolo',
            field=models.ManyToManyField(blank=True, null=True, to='gruppo.ruolo'),
        ),
    ]
