# Generated by Django 4.2.6 on 2023-12-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0029_alter_artisti_ruolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisti',
            name='ruolo',
        ),
    ]
