# Generated by Django 4.2.6 on 2023-12-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppo', '0030_remove_artisti_ruolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenti',
            name='data_inserimento',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
